### ISSUE TITLE
🐞 Bug: Netlify CI/CD fails with new preview builds

### ISSUE THREAD

**Issue by dileepadev-old** [nibmcs/nibmcs.org#21]
### Description

Encountered a bug related to our project's CI/CD workflow. The reason for removing Netlify is because it did not work seamlessly with the new Next.js version and consistently failed to build PR preview deployments.

### Steps to Reproduce

1. Create a new feature branch.
2. Make changes to the project code.
3. Push the branch to the repository.
4. Observe the CI/CD workflow.

### Expected Behavior

Expected the Netlify CI/CD workflow to successfully build and deploy the preview version of the project for the feature branch.

### Actual Behavior

The Netlify CI/CD workflow consistently failed to build and deploy the preview version of the project. This occurred after upgrading to the new Next.js version.

### Screenshots

Excising Issue:
![image](https://github.com/nibmcs/nibmcs.org/assets/80202913/a9038840-9ec6-4de6-8548-a40f28406a6c)

Vercel Integration:
![image](https://github.com/nibmcs/nibmcs.org/assets/80202913/a49f2129-807d-429d-81e6-8b24547490f0)

### Environment

- Operating System: Universal
- Browser: Universal
- Device: Universal
- Version: Node.js 18 & Next.js 13.5.x (Next.js 14 Ready)
- Other info: Not specific

### Additional Information

This bug report is being submitted in conjunction with a pull request that removes Netlify CI/CD and replaces it with Vercel CI/CD. **Changes will affect other feature branches as well as the dev branch.** The goal is to address the issues with Netlify and improve the project's CI/CD process.

**Comment by nibmcs-admin** [comment]
🐞 Checked 👍
